/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JkaAmbulanceWlList {
    }
}
declare global {
    interface HTMLJkaAmbulanceWlListElement extends Components.JkaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLJkaAmbulanceWlListElement: {
        prototype: HTMLJkaAmbulanceWlListElement;
        new (): HTMLJkaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "jka-ambulance-wl-list": HTMLJkaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface JkaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "jka-ambulance-wl-list": JkaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jka-ambulance-wl-list": LocalJSX.JkaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLJkaAmbulanceWlListElement>;
        }
    }
}
